spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: # seu email
    password: # sua  senha de app
    protocol: smtp
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          auth: true
          startlls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

  thymeleaf:
    enable: true

envio:
  email:
    remetente: # seu email
    nomeRemetente: 'Edson Vinicius'

server:
  port: 8082